### ISSUE TITLE
Example table not working, osqueryi 1.8.2

### ISSUE THREAD

**Issue by arubdesu** [osquery/osquery-python#27]
I've copy-pasted the exact `MyTablePlugin` example, renamed it with .ext, and get the following traceback when loading it as instructed in the ReadMe:
```py
Traceback (most recent call last):
  File "/Users/abanks/Desktop/MyTablePlugin.ext", line 26, in <module>
    osquery.start_extension(name="my_awesome_extension", version="1.0.0")
  File "/Library/Python/2.7/site-packages/osquery/management.py", line 184, in start_extension
    message=status.message,
osquery.extensions.ttypes.ExtensionException: ExtensionException(code=1, _message='Failed adding registry broadcast', uuid=None)
```

**Comment by arubdesu** [comment]
(My bad, wasn't running 1.8 version of module. Nothing to see here!)
