### ISSUE TITLE
No handlers could be found for logger "thrift.transport.TSocket"

### ISSUE THREAD

**Issue by prabhakarms** [osquery/osquery-python#37]
Have osquery service running - sud./build/debug_centos7/osquery/osqueryd --allow_unsafe  --pidfile /tmp/osquery.pid --database_path /tmp/osquery.db  --extensions_socket=/var/osquery/osquery.em
and would like execute queries on the running instance. Tried out the python example and running in to the following issue. Any thoughts ?
 
[vagrant@pdhillon-vm2 examples]$ python run.py 'select * from time'
No handlers could be found for logger "thrift.transport.TSocket"
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    RESULTS = CLIENT.extension_client().query(sys.argv[1])
  File "build/bdist.linux-x86_64/egg/osquery/extensions/ExtensionManager.py", line 184, in query
  File "build/bdist.linux-x86_64/egg/osquery/extensions/ExtensionManager.py", line 193, in send_query
  File "build/bdist.linux-x86_64/egg/thrift/transport/TTransport.py", line 177, in flush
  File "build/bdist.linux-x86_64/egg/thrift/transport/TSocket.py", line 138, in write
thrift.transport.TTransport.TTransportException: Transport not open
[vagrant@pdhillon-vm2 examples]$

**Comment by prabhakarms** [comment]
Got it working. It was just a permission issues.
